name: Push - Matrix Tests

on:
  push:
  workflow_dispatch:

jobs:
  test-on-os-node-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # due to node-gyp & node compatibility issues, windows 2022 won't work for all node versions
        node: [18, 20, 22]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}

    name: Test Node ${{ matrix.node }} on ${{ matrix.os }}

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: NPM Install
        run: npm install

      - name: Configure Windows 2019
        run: |
          echo "/c/Program Files/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          npm config set msvs_version 2019
        if: ${{ matrix.os == 'windows-2019' }}

      - name: Show Environment Info
        run: |
          printenv
          node --version
          npm --version

      - name: Run All Tests (against mock)
        run: npm test
        env:
          node_pre_gyp_mock_s3 : true

      - name: Run S3 Tests (against ${{ env.S3_BUCKET }} bucket)
        run: |
          npm run bucket ${{ env.S3_BUCKET }}
          npm run test:s3
        if: ${{ env.S3_BUCKET != '' }}

  test-nw:
    runs-on: ubuntu-18.04 # at current config the nw test requires python 2 as default. hence use older linux version
    strategy:
      matrix:
        node: [18, 20, 22]
        nw: [0.64.0, 0.50.2] # current version as of may 2022 and the one tested before introduction of this action.
    name: NW.js ${{ matrix.nw }} on Node ${{ matrix.node }}

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Run Script
        run: ./scripts/test-node-webkit.sh ${{ matrix.nw }}
